version: '3.8'
services:
  spektri:
    build: .
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    restart: always



