name: Advanced CI/CD Workflow with Full AI Integration

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  schedule:
    - cron: '0 0 * * 0'  # Weekly schedule to run the workflow
    - cron: '0 0 1 * *'  # Monthly schedule for dependency updates

jobs:
  validate_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Validate secrets
        run: |
          REQUIRED_SECRETS=("CODACY_PROJECT_TOKEN" "EMAIL_FALLBACK_URL" "OPENAI_API_KEY" "PAGERDUTY_KEY" "SLACK_WEBHOOK" "VERCEL_TOKEN" "GITHUB_TOKEN" "EMAIL_USERNAME" "EMAIL_PASSWORD" "EMAIL_RECIPIENT")
          for secret in "${REQUIRED_SECRETS[@]}"; do
            if [ -z "${{ secrets[$secret] }}" ]; then
              echo "::error::$secret is not set"
              exit 1
            fi
          done


