name: Ultimate Advanced CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  schedule:
    - cron: '0 0 * * 0'  # Weekly schedule to run the workflow
    - cron: '0 0 1 * *'  # Monthly schedule for dependency updates

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Secrets
        id: validate-secrets
        run: |
          REQUIRED_SECRETS=("CODACY_PROJECT_TOKEN" "OPENAI_API_KEY" "PAGERDUTY_KEY" "SLACK_WEBHOOK" "VERCEL_TOKEN" "GITHUB_TOKEN" "SNYK_TOKEN" "CODECOV_TOKEN" "CYPRESS_RECORD_KEY")
          for secret in "${REQUIRED_SECRETS[@]}"; do
            if [ -z "${{ secrets[${secret}] }}" ]; then
              echo "::error::$secret is not set. Please set the secret and try again."
              exit 1
            fi
          done

